---
- name: Install Development Dependencies
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - "bash-completion"
    - "curl"
    - "git"
    - "htop"
    - "vim"
    - "netcat"
    - "borgbackup"
    - "python3"
    - "python-pip"

- name: Add Vim global vimrc
  template:
    src: "global_vimrc.j2" 
    dest: "/etc/vim/vimrc"

- name: Install pip packages for docker
  pip:
    name: "{{ item }}"
    state: forcereinstall
  loop:
    - "docker"

- name: Remove pip Packages for docker
  pip:
    name: "{{ item }}"
    state: absent
  loop:
    - "docker-py"
