---
- name: Install Development Dependencies
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - "*"
    - "git"
    - "vim"
    - "netcat"
    - "python3"
    - "borgbackup"
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"
    - "python3"
    - "python3-pip"

- name: Install pip Packages
  pip:
    executable: "/usr/bin/pip3"
    name: "{{ item }}"
    state: forcereinstall
  loop:
    - "docker"

- name: Install pip Packages
  pip:
    executable: "/usr/bin/pip3"
    name: "{{ item }}"
    state: absent
  loop:
    - "docker-py"
