---
roles:
  - name: darkwizard242.speedtest
    version: 2.0.0
  - name: kyl191.openvpn
    version: v0.9.1
  - name: m3nu.ansible_role_borgbackup
    version: v0.8.1
  - name: githubixx.ansible_role_wireguard
    version: 8.4.0
  - name: geerlingguy.docker
    version: 4.1.1

collections:
  - name: kewlfft.aur
    version: 0.10.0
  - name: community.crypto
    version: 1.9.5
