---
### Installing 1Password

- name: Add gpg key for 1Password
  shell: "curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import"
  register: one_pass_gpg
  become: yes
  become_user: pkg-builder

### Installing Spotify
- name: Add gpg key for Spotify
  shell: "curl -sS https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg | gpg --import -"
  become: yes
  become_user: pkg-builder

- name: Installing Applications
  become: yes
  become_user: pkg-builder
  kewlfft.aur.aur:
    name: "{{item}}"
  loop:
    - "1password"
    - "spotify"

