---
- name: Create pkg-builder group
  group:
    name: pkg-builder

- name: Create pkg-builder user
  become: yes
  user:
    name: pkg-builder
    shell: /bin/bash
    group: pkg-builder

- name: Allow the `pkg_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-pkg-builder
    line: 'pkg-builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Install Development Dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - "curl"
    - "docker"
    - "firefox"
    - "git"
    - "htop"
    - "man"
    - "neofetch"
    - "netcat"
    - "python-pip"
    - "python3"
    - "vim"
    - "code"
    - "keepassxc"
    - "zsh"

- name: Install pip dependencies
  pip: 
    name: "{{item}}"
    state: latest
  loop:
    - "pykeepass"

- name: Add Vim global vimrc
  template:
    src: "global_vimrc.j2" 
    dest: "/etc/vimrc"

- name: Add profile files to be sourced
  template:
    src: "etc_bashrc.j2"
    dest: "/etc/bash.bashrc"


- name: enable systemd services
  systemd:
    name: "{{item}}"
    enabled: true
    state: started
  loop:
    - "docker"

- name: remove gnome bloat
  package:
    state: "absent"
    name: "{{item}}"
  loop:
    - "gnome-contacts"
    - "gnome-music"
    - "gnome-photos"
    - "gnome-books"
    - "gnome-maps"
    - "gnome-calendar"

