---
- name: Create pkg-builder group
  group:
    name: pkg-builder

- name: Create pkg-builder user
  user:
    name: pkg-builder
    shell: /bin/bash
    group: pkg-builder

- name: Allow the `pkg_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-pkg-builder
    line: 'pkg-builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Install Development Dependencies
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - "alacritty"
    - "curl"
    - "docker"
    - "firefox"
    - "git"
    - "htop"
    - "man"
    - "neofetch"
    - "netcat"
    - "python-pip"
    - "python3"
    - "vim"
    - "code"
    - "keepassxc"

- name: Install pip dependencies
  pip: 
    name: "{{item}}"
    state: latest
  loop:
    - "pykeepass"

- name: Add Vim global vimrc
  template:
    src: "global_vimrc.j2" 
    dest: "/etc/vimrc"

- name: Add Alacritty config file
  become: yes
  become_user: jlumley
  template:
    src: "global_alacritty_conf.j2"
    dest: "/home/jlumley/.alacritty.yml"

- name: Add profile files to be sourced
  template:
    src: "etc_bashrc.j2"
    dest: "/etc/bash.bashrc"


- name: Fetch Package Repositories
  git:
    repo: "{{item.repo}}"
    dest: "/tmp/{{item.name}}"
    version: "{{item.version}}"
    clone: yes
    force: yes
  loop: 
    - name: "xclip"
      repo: "https://github.com/astrand/xclip.git"
      version: "master"

- name: Install xclip
  command:
    chdir: "/tmp/xclip"
    cmd: "{{item}}"
  loop:
    - "autoreconf"
    - "./configure"
    - "make"
    - "make install"
    - "make install.man"

- name: enable systemd services
  systemd:
    name: "{{item}}"
    enabled: true
    state: started
  loop:
    - "docker"

- name: remove gnome bloat
  package:
    state: "absent"
    name: "{{item}}"
  loop:
    - "gnome-contacts"
    - "gnome-music"
    - "gnome-photos"
    - "gnome-books"
    - "gnome-maps"
    - "gnome-calendar"

