# Creating the following Containers:
# - unifi-controller
# - nginx
# - dashmachine
# - mosquitto
# - home-assistant
# - frigate
# - budgetzero

- name: Deploy Unifi Controller
  docker_container:
    name: unifi-controller
    image: ghcr.io/linuxserver/unifi-controller
    pull: "{{ update_containers }}"
    restart_policy: "always"
    dns_servers:
      - "{{ dns_server }}"
    env:
      PUID: "2010"
      PGID: "2010"
    mounts:
      - source: "/srv/config/unifi"
        target: "/config"
        type: bind
    published_ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 1900:1900/udp
      - 6789:6789
      - 5514:5514
      - 8080:8080
      - 8443:8443

- name: Deploy Niginx
  docker_container:
    name: nginx
    image: ghcr.io/linuxserver/swag
    pull: "{{ update_containers }}"
    restart_policy: "always"
    dns_servers:
      - "{{ dns_server }}"
    env:
      PUID: "2006"
      PGID: "2007"
      URL: local.jlumley.com
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: cloudflare
    mounts:
      - source: "/srv/config/nginx/conf"
        target: "/config"
        type: bind
      - source: "/srv/config/nginx/cloudflare.ini"
        target: "/config/dns-conf/cloudflare.ini"
        read_only: yes
        type: bind
    network_mode: host

- name: Deploy Mosquitto MQTT
  docker_container:
    name: mosquitto-mqtt
    image: eclipse-mosquitto
    pull: "{{ update_containers }}"
    restart_policy: "always"
    network_mode: host
    dns_servers:
      - "{{ dns_server }}"
    env:
      PUID: "1883"
      PGID: "1883"
    mounts:
      - source: "/srv/config/mosquitto"
        target: "/mosquitto"
        type: bind

- name: Deploy Frigate
  docker_container:
    name: frigate
    image: blakeblackshear/frigate:stable-amd64
    pull: "{{ update_containers }}"
    restart_policy: "always"
    network_mode: host
    privileged: true
    dns_servers:
      - "{{ dns_server }}"
    env:
      TZ: "America/Toronto"
      FRIGATE_RTSP_PASSWORD: "this-is-the-way"
      PUID: "2022"
      PGID: "2022"
    mounts:
      - source: "/etc/localtime"
        target: "/etc/localtime"
        read_only: yes
        type: bind
      - source: "/srv/config/frigate/config"
        target: "/config"
        type: bind
      - source: "/data/frigate"
        target: "/media/frigate"
        type: bind
      - target: /tmp/cache
        type: tmpfs
        tmpfs_size: 1G

- name: Deploy Home Assistant
  docker_container:
    name: home-assistant
    image: ghcr.io/linuxserver/homeassistant
    pull: "{{ update_containers }}"
    restart_policy: "always"
    network_mode: host
    dns_servers:
      - "{{dns_server}}"
    env:
      TZ: "America/Toronto"
      PUID: "2009"
      PGID: "2009"
    mounts:
      - source: "/srv/config/home-assistant"
        target: "/config"
        type: bind

- name: Deploy Dash Machine
  docker_container:
    name: dashboard
    image: rmountjoy/dashmachine
    pull: "{{update_containers}}"
    restart_policy: "always"
    dns_servers:
      - "{{dns_server}}"
    mounts:
      - source: "/srv/config/dashboard"
        target: "/dashmachine/dashmachine/user_data"
        type: bind
    published_ports:
      - 5005:5000


