---
- name: Setup Arch Linux
  hosts: localhost
  gather_facts: true

  roles:
    - name: Install Packages for Arch
      role: arch_packages
    
    - name: Install Arch Desktop Apps
      role: desktop_apps

    - name: Set GNOME Custom Apperance
      role: desktop_appearance

