---
- name: Setup Arch Linux
  hosts: localhost
  gather_facts: true
  
  vars_prompt:
    - name: is_macbook
      prompt: is this a macbook? [y/N] 
      private: no
      default: "n"


  roles:
    - name: Install Packages for Arch
      role: arch_packages
    
    - name: Install Arch Desktop Apps
      role: desktop_apps

    - name: Install Requirements for Macbooks
      role: macbook_arch
      when: is_macbook == "y" 




