---
- name: Set up Docker Containers for local infrastructure
  hosts: jlumley-r710-01.jlumley.local

  vars_prompt:
    - name: update_containers
      prompt: "Pull new docker images? (yes/no)"
      private: no
    - name: pia_password
      prompt: "PIA Password"
      private: no
    - name: plex_claim
      prompt: "Plex Claim"
      private: no

  roles:
    - name: Install dependencies
      role: common

    - name: Deploy Infrastructure Docker containers
      role: infrastructure_containers

    - name: Deploy Media Docker containers
      role: media_containers
