---
- name: Set up Docker Containers for local infrastructure
  hosts: r710-01.jlumley.local

  vars_prompt:
    - name: update_containers
      prompt: "Pull new docker images? (yes/no)"
      private: no
    - name: keepass_pw
      prompt: "Enter KeePass Password"

  pre_tasks:
    - name: "PIA Secrets"
      keepassxc:
        database: "/secrets/Passwords.kdbx"
        password: "{{keepass_pw}}"
        entry: "private_internet_access"
      register: "pia_secrets"
      delegate_to: "localhost"

    - name: "Plex Secrets"
      keepassxc:
        database: "/secrets/Passwords.kdbx"
        password: "{{keepass_pw}}"
        entry: "plex"
      register: "plex_secrets"
      delegate_to: "localhost"

    - name: "Cloudflare Secrets"
      keepassxc:
        database: "/secrets/Passwords.kdbx"
        password: "{{keepass_pw}}"
        entry: "cloudflare"
      register: "cloudflare_secrets"
      delegate_to: "localhost"

    - name: "MQTT Secrets"
      keepassxc:
        database: "/secrets/Passwords.kdbx"
        password: "{{keepass_pw}}"
        entry: "mqtt"
      register: "mqtt_secrets"
      delegate_to: "localhost"
    
    - name: "Amcrest Secrets"
      keepassxc:
        database: "/secrets/Passwords.kdbx"
        password: "{{keepass_pw}}"
        entry: "amcrest"
      register: "amcrest_secrets"
      delegate_to: "localhost"
    
    - name: "Zigbee2MQTT Secrets"
      keepassxc:
        database: "/secrets/Passwords.kdbx"
        password: "{{keepass_pw}}"
        entry: "zigbee2mqtt"
      register: "zigbee2mqtt_secrets"
      delegate_to: "localhost"




  roles:
    - common
    - infrastructure_containers
    - media_containers
    - container_restart
