---
- name: Setup r710-01.jlumley.local
  hosts: r710-01.jlumley.local
  gather_facts: true

  vars_prompt:
    - name: keepass_pw
      prompt: Enter Password for KeePass Database 

  # Fetch Secrets from KeePassXC 
  pre_tasks:
    - name: BorgBase.com
      keepassxc:
        database: "/secrets/Passwords.kdbx"
        password: "{{keepass_pw}}"
        entry: "borg_base"
      register: borg_base_secrets
      delegate_to: jeremy-arch-desktop.jlumley.local

    - name: foo
      debug:
        msg: "secrets: {{borg_base_secrets}}" 
  
  roles:
    - name: Install Common Development Tools
      role: common

    - name: Install speedtest-cli
      role: darkwizard242.speedtest

    - name: Add users
      role: add_users

    - name: Set up Borg Backups
      role: borg_backup

    - name: Install Docker-ce
      role: geerlingguy.docker
